apiVersion: v1
kind: Pod
metadata:
  name: secure-user-pod
  namespace: audit-zone
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: nginx
      image: nginxinc/nginx-unprivileged:latest
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true  
        runAsUser: 101
        capabilities:
          drop: ["ALL"]