apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPrivContainers
metadata:
  name: deny-privileged-containers
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - audit-zone
